Repository ayazhafiz/hgb, pull requests merged in 2020-01, with the labels that each got.

#14 Lukas
  src/Builtin.hs
  src/Symbol.hs
  src/Token.hs
Labels: effort:trivial

#17 Minor fixups to make hlint happy
  hgb.cabal
  src/Lexer.hs
Labels: effort:trivial, type:refactor

#18 Removed Char functionality from Gingerbread
  hgb.cabal
  src/Builtin.hs
  src/Symbol.hs
  test/Lexer/LexerSpec.hs
Labels: effort:trivial

#22 fix: lex operator combinations separately
  hgb.cabal
  src/Builtin.hs
  src/Lexer.hs
  src/Symbol.hs
  test/Lexer/LexerSpec.hs
Labels: effort:subhour, type:bug

#23 e: add support for lexing floating point numbers
  hgb.cabal
  src/Lexer.hs
  test/Lexer/LexerSpec.hs
Labels: effort:trivial, type:feature
